apiVersion: apps/v1
kind: {{.Values.kind.type1}}
metadata:
  creationTimestamp: null
  labels:
    app: {{.Values.labels.app}}
  name: {{.Values.labels.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.labels.name}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{.Values.labels.app}}
    spec:
      containers:
      - image: {{.Values.image}}
        name: {{.Values.containername}}
        resources: {}
status: {}
