apiVersion: v1
kind: {{.Values.kind.type2}}
metadata:
  labels:
    app: {{ .Values.service.labels.app}}
  name: {{ .Values.service.labels.name}}
spec:
  type: {{ .Values.service.type}}
  ports:
  - port: {{ .Values.service.port}}
    protocol: {{ .Values.service.protocol}}
    targetPort: {{ .Values.service.targetPort}}
  selector:
    app: {{ .Values.service.selector.app}}